server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    # Laravel sert tout depuis le dossier /public

    index index.php;

    # Toutes les requêtes passent par index.php (routing Laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM traite les fichiers .php
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # On ignore les fichiers cachés (.env, .git…)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
