[supervisord]
nodaemon=true
; nodaemon=true : supervisor reste au premier plan (obligatoire dans Docker)

[program:php-fpm]
command=php-fpm
; Lance PHP-FPM pour traiter les fichiers PHP
autostart=true
autorestart=true
; Redémarre automatiquement si le processus plante

[program:nginx]
command=nginx -g "daemon off;"
; Lance Nginx en premier plan (obligatoire dans Docker)
autostart=true
autorestart=true
